<div id="logon">

<div align="center">
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'logon'));?>" id="logonselected">商家登录</a>
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'testerlogon'));?>" id="logonunselected">测试人员登录</a>
</div>
<div id="logonbody" align="center">
	<div id="loginTable">
		<form action="<?php echo $this->url(array('controller' => 'logon', 'action'=>'logon')); ?>"
			name="form" method="post" onsubmit="return _validate();">
			<input type="hidden" name="back" value="<?php echo $this->backpage;?>"/>
			<table>
				<tr>
					<td></td>
					<td><?php echo $this->escape($this->ttt);?></td>
				</tr>
				<tr>
					<td>用户名：</td>
					<td><input type="text" name="username" id="username"></td>
				</tr>
				<tr>
					<td>密码：</td>
					<td><input type="password" name="password" id="password"></td>
				</tr>
				<tr>
					<td></td>
					<td><input type="submit" name="submit" id="submit" value="登陆"> <a
						href="<?php
						
echo $this->url ( array (
								'controller' => 'logon',
								'action' => 'register' 
						) );
						?>">注册</a></td>
				</tr>
			</table>
		</form>
	</div>
</div>
</div>
<script>
//验证表单是否为空
function _validate(){
 if(document.getElementById('username').value==""){
  alert("请输入账户名");
  document.getElementById('username').focus();
  return false;
 }else{
  if(document.getElementById('password').value==""){
   alert("请输入密码");
   document.getElementById('password').focus();
   return false;
  }
 }
 return true;
}
</script>