<div id="logon">

<div align="center">
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'logon'));?>" id="logonunselected">商家登录</a>
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'testerlogon'));?>" id="logonselected">测试人员登录</a>
</div>
<div id="logonbody" align="center">
	<div id="loginTable">
		<form
			action="<?php echo $this->url(array('controller' => 'logon', 'action'=>'testerlogon')); ?>"
			name="form" method="post" onsubmit="return _validate();">
			<input type="hidden" name="back" value="<?php echo $this->backpage;?>"/>
			<table>
				<tr>
					<td></td>
					<td><?php echo $this->escape($this->ttt);?></td>
				</tr>
				<tr>
					<td>用户名：</td>
					<td><input type="text" name="testername" id="testername"></td>
				</tr>
				<tr>
					<td>密码：</td>
					<td><input type="password" name="password" id="password"></td>
				</tr>
				<tr>
					<td></td>
					<td><input type="submit" name="submit" id="submit" value="登陆"> <a
						href="<?php
							
echo $this->url ( array (
									'controller' => 'logon',
									'action' => 'testerregister' 
							) );
							?>">注册</a></td>
				</tr>
			</table>
		</form>
	</div>
</div>
</div>
<script>
//验证表单是否为空
function _validate(){
 if(document.getElementById('testername').value==""){
  alert("请输入账户名");
  document.getElementById('testername').focus();
  return false;
 }else{
  if(document.getElementById('password').value==""){
   alert("请输入密码");
   document.getElementById('password').focus();
   return false;
  }
 }
}
</script>