<?php 
   echo '案例中心';
?>

<table>

<?php if($_SESSION['have_result'] == 'yes') {?>
<tr>
    <th>任务编号</th>
    <th>任务名称</th>
    <th>商家姓名</th>
    <th>测试人员</th>
    <th>技术范围</th>
    <th>关于</th>
    <th>内容</th>
    <th>成交金额</th>
    <th>父任务</th>
    <th>前任务</th>
    <th>商家被评分</th>
    <th>测试人员时间得分</th>
    <th>测试人员质量得分</th>
    <th>测试人员服务得分</th>
    <th>发布时间</th>
    <th>期限</th>
    <th>申请时间</th>
    <th>同意申请时间</th>
    <th>开始测试时间</th>
    <th>完成测试时间</th>
    <th>结束时间</th>
</tr>
<?php } else{}?>

<?php  foreach($this->result as $value) :  ?>
<tr>
    <td><?php echo $this->escape($value['Mission_ID']);?></td>
    <td> <?php echo $this->escape($value['Mission_Name']);?></td>
    <td><?php echo $this->escape($value['Release_User']);?></td>
    <td><?php echo $this->escape($value['Tester']);?></td>
    <td><?php echo $this->escape($value['Tec_Field']);?></td>
    <td><?php echo $this->escape($value['Mission_About']);?></td>
    <td><?php echo $this->escape($value['Mission_Content']);?></td>
    <td><?php echo $this->escape($value['Price']);?></td>
    <td><?php echo $this->escape($value['Father_Mission']);?></td>
    <td><?php echo $this->escape($value['Pre_Mission']);?></td>
    <td><?php echo $this->escape($value['User_Givenscore']);?></td>
    <td><?php echo $this->escape($value['Tester_Giventimingscore']);?></td>
    <td><?php echo $this->escape($value['Tester_Givenqualityscore']);?></td>
    <td><?php echo $this->escape($value['Tester_Givenmatescore']);?></td>
    <td><?php echo $this->escape($value['Release_Time']);?></td>
    <td><?php echo $this->escape($value['Tofinish_Time']);?></td>
    <td><?php echo $this->escape($value['Applied_Time']);?></td>
    <td><?php echo $this->escape($value['Agreed_Time']);?></td>
    <td><?php echo $this->escape($value['Start_Time']);?></td>
    <td><?php echo $this->escape($value['Finished_Time']);?></td>
    <td><?php echo $this->escape($value['End_Time']);?></td>
    
    
</tr>
<?php endforeach; ?>

</table>



<h1> <?php echo $this->escape($this->message);?></h1>