<?php 
   echo '案例中心';
?>

<style>

.recordid{
	
	font-weight: bold;
	color:#9393FF;
	font-family: Helv;
	
}
</style>
<style>
.keyword {
	margin: 10px;
	width: 50px;
	font-size: 13px;
}
.keyworddiv {
	
}
</style>
<hr />
关键字：
<div class="keyworddiv" style="width: 760px;">

<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '集成测试'));?>" class="keyword">集成测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '系统测试'));?>" class="keyword">系统测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '功能测试'));?>" class="keyword">功能测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '安全性测试'));?>" class="keyword">安全性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '容量测试'));?>" class="keyword">容量测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '完整性测试'));?>" class="keyword">完整性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '结构测试'));?>" class="keyword">结构测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '用户界面测试'));?>" class="keyword">用户界面测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '负载测试'));?>" class="keyword">负载测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '压力测试'));?>" class="keyword">压力测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '疲劳强度测试'));?>" class="keyword">疲劳强度测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '恢复性测试'));?>" class="keyword">恢复性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '配置测试'));?>" class="keyword">配置测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '兼容性测试'));?>" class="keyword">兼容性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '安装测试'));?>" class="keyword">安装测试</a>
<a href="<?php echo $this->url(array('action' => 'searchrecord', 'selected' => 'ForRecord', 'keyword' => '其他测试'));?>" class="keyword">其他测试</a>
</div>


<div id = 'allrecords'>

<?php  foreach($this->result as $value) :  ?>
<hr />
<ul style="padding-left: 0px;">
 
 <li>
    <span class='recordid'>[<?php echo $this->escape($value['Mission_ID']);?>]  </span>
    <span>  <a href="<?php echo $this->url(array('controller'=>'index', 
          'action'=>'recorddetail', 'fordetail_recordid' => $value['Mission_ID'] ));?>"><?php echo $this->escape($value['Mission_Name']);?></a></span>
    <span>  商家      <a href="<?php echo $this->url(array('controller' => 'index',
    		'action' => 'userdetail', 'fordetail_userid' => $value['Release_User']));?>"><?php echo $this->escape($this->getAccountNameById($value['Release_User']));?></a></span>
    <span>   测试人员   <a href="<?php echo $this->url(array('controller' => 'index',
    		'action' => 'testerdetail', 'fordetail_testerid' => $value['Release_User']));?>"><?php echo $this->escape($this->getAccountNameById($value['Tester']));?></a></span>
 </li>
 <li>
    <span style="float: right; width: 100px;"> ￥<?php if($value['Price'])
    													echo $this->escape($value['Price']);
    													else echo '结账中'			?></span>
   
 </li>
 <li>
    <span>发布：  <?php echo substr($this->escape($value['Release_Time']),0,10);?></span>
    
    
    <span> 完成交易： <?php echo substr($this->escape($value['Finished_Time']),0,10);?></span>
    
 </li>
 <li>
     <span> 简介  <?php echo $this->escape($value['Mission_About']);?> </span>
 </li>
</ul>

<?php endforeach; ?>


</div>

