<?php
   echo '商家中心';
?>
<table>

<?php if($_SESSION['have_result'] == 'yes') {?>
<tr>
    <th>账户编号</th>
    <th>姓名</th>
    <th>邮箱</th>
    <th>图片</th>
    <th>性别</th>
    <th>手机号</th>
    <th>自我评价</th>
    <th>合作数量</th>
    <th>评分</th>
</tr>
<?php } else{}?>

<?php  foreach($this->result as $value) :  ?>
<tr>
    <td><?php echo $this->escape($value['Account_ID']);?></td>
    <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'userdetail', 'fordetail_userid' => $value['Account_ID'] ));?>"><?php echo $this->escape($value['Account_Name']);?></a></td>
    <td><?php echo $this->escape($value['Account_Email']);?></td>
    <td><?php echo $this->escape($value['Account_Icon']);?></td>
    <td><?php echo $this->escape($value['Account_Sex']);?></td>
    <td><?php echo $this->escape($value['Account_mobile']);?></td>
    <td><?php echo $this->escape($value['Self_Discription']);?></td>

    <td><?php echo $this->getUserSubCountsById($value['Account_ID']);?></td>
    <td><?php echo $this->getUserScoreById($value['Account_ID']);?></td>
</tr>
<?php endforeach; ?>

</table>