<?php
   echo '项目中心';
?>

<table>

<?php if($_SESSION['have_result'] == 'yes') {?>
<tr>
    <th>任务编号</th>
    <th>任务名称</th>
    <th>发布时间</th>
    <th>申请截止</th>
    <th>任务截止</th>
    <th>技术范围</th>
    <th>关于</th>
    <th>最低价</th>
    <th>最高价</th>
    <th>任务类型</th>
    <th>内容</th>
    <th>父任务</th>
    <th>前任务</th>
</tr>
<?php } else{}?>

<?php  foreach($this->result as $value) :  ?>
<tr>
    <td><?php echo $this->escape($value['Mission_ID']);?></td>
    <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'missiondetail', 'fordetail_missionid' => $value['Mission_ID'] ));?>"><?php echo $this->escape($value['Mission_Name']);?></a></td>
    <td><?php echo $this->escape($value['Release_Time']);?></td>
    <td><?php echo $this->escape($value['Apply_Deadline']);?></td>
    <td><?php echo $this->escape($value['Finish_Deadline']);?></td>
    <td><?php echo $this->escape($value['Tec_Field']);?></td>
    <td><?php echo $this->escape($value['Mission_About']);?></td>
    <td><?php echo $this->escape($value['Lowest_Price']);?></td>
    <td><?php echo $this->escape($value['Highest_Price']);?></td>
    <td><?php echo $this->escape($_SESSION['test_num_str'][$value['Mission_State']]);?></td>
    <td><?php echo $this->escape($value['Mission_Content']);?></td>
    <td><?php echo $this->escape($value['Father_Mission']);?></td>
    <td><?php echo $this->escape($value['Pre_Mission']);?></td>
    
    
</tr>
<?php endforeach; ?>


</table>