
<div id="welcome">
<!-- 
<h2 align="center"><a href="<?php echo $this->url(array('controller'=>'publishmission', 
        'action'=>'chooseredirector'));?>">发布任务</a></h2>
<p align="center"><a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'logon'));?>" >测试商家登录</a>
        <a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'register'));?>">注册</a></p>
<p align="center"><a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'testerlogon'));?>" >测试人员登录</a>
        <a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'testerregister'));?>">注册</a></p> -->
<div>
        <h2 style="font-size: 10px;">已完成的任务</h2>
	<table>
		<tr>
			<th>任务编号</th>
			<th>任务名称</th>
			<th>任务类型</th>
			<th>任务发布时间</th>
			<th>父任务</th>
		</tr>
<?php foreach ($this->missionscompleted as $um) :?>
		<tr>
			<td><?php echo $this->escape($um['Mission_ID']);?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'mission', 'missionid' => $um['Mission_ID']));?>"><?php echo $this->escape($um['Mission_Name']);?></a></td>
			<td><?php echo $this->escape($_SESSION['test_num_str'][$um['Mission_State']]);?></td>
			<td><?php echo $this->escape($um['Release_Time']);?></td>
			<td><?php echo $this->escape($um['Father_Mission'])?$this->escape($um['Father_Mission']):'X';?></td>
		</tr>
<?php endforeach;?>
	</table>
</div>
<div>
        <h2 style="font-size: 10px;">测试中的任务</h2>
	<table>
		<tr>
			<th>任务编号</th>
			<th>任务名称</th>
			<th>任务类型</th>
			<th>任务发布时间</th>
			<th>父任务</th>
		</tr>
<?php foreach ($this->missionstesting as $um) :?>
		<tr>
			<td><?php echo $this->escape($um['Mission_ID']);?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'mission', 'missionid' => $um['Mission_ID']));?>"><?php echo $this->escape($um['Mission_Name']);?></a></td>
			<td><?php echo $this->escape($_SESSION['test_num_str'][$um['Mission_State']]);?></td>
			<td><?php echo $this->escape($um['Release_Time']);?></td>
			<td><?php echo $this->escape($um['Father_Mission'])?$this->escape($um['Father_Mission']):'X';?></td>
		</tr>
<?php endforeach;?>
	</table>
</div>
<!-- 
<div  align="center">
        <h3>项目制作人：</h3>
   <p>	<font size="2" color="SandyBrown">元东</font><img src="<?php echo $this->baseUrl();?>/image/2.jpg" width="100" height="75"/> 
		<font size="2" color="SandyBrown">沈明</font><img src="<?php echo $this->baseUrl();?>/image/3.jpg" width="100" height="75"/>
		<font size="2" color="SandyBrown">李昊桦</font><img src="<?php echo $this->baseUrl();?>/image/4.jpg" width="100" height="75"/>
      	<font size="2" color="SandyBrown">钟浩健</font><img src="<?php echo $this->baseUrl();?>/image/6.jpg" width="100" height="75"/>
   		<font size="2" color="SandyBrown">王骁</font><img src="<?php echo $this->baseUrl();?>/image/7.jpg" width="125" height="75"/></p>
</div> -->
</div>