<style>
.littletext {
	font-size: 10px;
	color: gray;
}
.littlecontent {
	width: 150px;
	display:inline-block;
}
</style>


<div id="welcome">
<!-- 
<h2 align="center"><a href="<?php echo $this->url(array('controller'=>'publishmission', 
        'action'=>'chooseredirector'));?>">发布任务</a></h2>
<p align="center"><a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'logon'));?>" >测试商家登录</a>
        <a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'register'));?>">注册</a></p>
<p align="center"><a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'testerlogon'));?>" >测试人员登录</a>
        <a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'testerregister'));?>">注册</a></p> -->
<div style="margin-top: 75px;">
        <h2 style="font-size: 10px;">已完成的任务</h2>

<?php foreach ($this->missionscompleted as $value) :?>

<hr />
<ul style="padding-left: 0px;">
 
 <li>
    <span class='recordid'>[<?php echo $this->escape($value['Mission_ID']);?>]  </span>
    <span>  <a href="<?php echo $this->url(array('controller'=>'index', 
          'action'=>'recorddetail', 'fordetail_recordid' => $value['Mission_ID'] ));?>"><?php echo $this->escape($value['Mission_Name']);?></a></span>
    <span style="float: right; width: 100px;"> ￥<?php if($value['Price'])
    													echo $this->escape($value['Price']);
    													else echo '结账中'			?></span>
 </li>
 <li>
   
    <span class="littlecontent">  商家      <a href="<?php echo $this->url(array('controller' => 'index',
    		'action' => 'userdetail', 'fordetail_userid' => $value['Release_User']));?>"><?php echo $this->escape($this->getAccountNameById($value['Release_User']));?></a></span>
    <span class="littlecontent"> 测试人员  <a href="<?php echo $this->url(array('controller' => 'index',
    		'action' => 'testerdetail', 'fordetail_testerid' => $value['Release_User']));?>"><?php echo $this->escape($this->getAccountNameById($value['Tester']));?></a></span>
   <span class="littlecontent">  <span class="littletext">任务类型：</span>  <?php echo $this->escape($_SESSION['test_num_str'][$value['Mission_State']]);?></span>
 </li>
 <li>
    <span class="littlecontent"><span class="littletext">发布：</span>  <?php echo substr($this->escape($value['Release_Time']),0,10);?></span>
    
    
    <span> <span class="littletext">完成交易：</span> <?php echo substr($this->escape($value['Finished_Time']),0,10);?></span>
    
 </li>
 <li>
     <span> 简介  <?php echo $this->escape($value['Mission_About']);?> </span>
 </li>
</ul>
<?php endforeach;?>
</div>
<div>
        <h2 style="font-size: 10px;">测试中的任务</h2>
<?php foreach ($this->missionstesting as $value) :?>
<hr />
<ul style="padding-left: 0px;">
 <li>
   <span class='missionid'>[<?php echo $this->escape($value['Mission_ID']);?>]</span>
   <span>  <a href="<?php echo $this->url(array('controller'=>'index', 
          'action'=>'missiondetail', 'fordetail_missionid' => $value['Mission_ID'] ));?>"><?php echo $this->escape($value['Mission_Name']);?></a> </span>
   <span style='float:right'>￥ <?php echo $this->escape($value['Lowest_Price']);?>~￥  <?php echo $this->escape($value['Highest_Price']);?></span>
 </li>
 
 <li>
   
   
   <span style='float:left' class="littlecontent">  <span class="littletext">发布</span>  <?php echo substr($this->escape($value['Release_Time']),0,10);?></span>

   <span style='float: right;' class="littlecontent"> <span class="littletext">截止</span>  <?php echo substr($this->escape($value['Finish_Deadline']),0,10);?></span>
 </li>
 
 <li><span class="littlecontent">  <span class="littletext">任务类型：</span>  <?php echo $this->escape($_SESSION['test_num_str'][$value['Mission_State']]);?></span>
   
   
   <span><span class="littletext">技术领域：</span><?php echo $this->escape($value['Tec_Field']);?></span>
   
 </li>
 <li>
   <span>简介   <?php echo $this->escape($value['Mission_About']);?></span>
 </li>
</ul>
<?php endforeach;?>
</div>
<!-- 
<div  align="center">
        <h3>项目制作人：</h3>
   <p>	<font size="2" color="SandyBrown">元东</font><img src="<?php echo $this->baseUrl();?>/image/2.jpg" width="100" height="75"/> 
		<font size="2" color="SandyBrown">沈明</font><img src="<?php echo $this->baseUrl();?>/image/3.jpg" width="100" height="75"/>
		<font size="2" color="SandyBrown">李昊桦</font><img src="<?php echo $this->baseUrl();?>/image/4.jpg" width="100" height="75"/>
      	<font size="2" color="SandyBrown">钟浩健</font><img src="<?php echo $this->baseUrl();?>/image/6.jpg" width="100" height="75"/>
   		<font size="2" color="SandyBrown">王骁</font><img src="<?php echo $this->baseUrl();?>/image/7.jpg" width="125" height="75"/></p>
</div> -->
</div>