<h1 align="center">登陆</h1>
<div id="bodyDiv" align="center">
	<div id="loginTable">
		<form action="<?php echo $this->url(array('action'=>'logon')); ?>"
			name="form" method="post" onsubmit="return _validate();">
			<table>
				<tr>
					<td></td>
					<td><?php echo $this->escape($this->ttt);?></td>
				</tr>
				<tr>
					<td>用户名：</td>
					<td><input type="text" name="username" id="username"></td>
				</tr>
				<tr>
					<td>密码：</td>
					<td><input type="password" name="password" id="password"></td>
				</tr>
				<tr>
					<td></td>
					<td><input type="submit" name="submit" id="submit" value="登陆"> <a
						href="<?php
						
echo $this->url ( array (
								'controller' => 'index',
								'action' => 'register' 
						) );
						?>">注册</a></td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script>
//验证表单是否为空
function _validate(){
 if(document.getElementById('username').value==""){
  alert("请输入账户名");
  document.getElementById('username').focus();
  return false;
 }else{
  if(document.getElementById('password').value==""){
   alert("请输入密码");
   document.getElementById('password').focus();
   return false;
  }
 }
 return true;
}
</script>