

<style>

.missionid{
	
	font-weight: bold;
	color:#9393FF;
	font-family: Helv;
	
}
</style>

<style>
.keyword {
	margin: 10px;
	width: 50px;
	font-size: 13px;
}
.keyworddiv {
	
}
</style>
<hr />
关键字：
<div class="keyworddiv" style="width: 760px;">

<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '集成测试'));?>" class="keyword">集成测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '系统测试'));?>" class="keyword">系统测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '功能测试'));?>" class="keyword">功能测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '安全性测试'));?>" class="keyword">安全性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '容量测试'));?>" class="keyword">容量测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '完整性测试'));?>" class="keyword">完整性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '结构测试'));?>" class="keyword">结构测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '用户界面测试'));?>" class="keyword">用户界面测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '负载测试'));?>" class="keyword">负载测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '压力测试'));?>" class="keyword">压力测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '疲劳强度测试'));?>" class="keyword">疲劳强度测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '恢复性测试'));?>" class="keyword">恢复性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '配置测试'));?>" class="keyword">配置测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '兼容性测试'));?>" class="keyword">兼容性测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '安装测试'));?>" class="keyword">安装测试</a>
<a href="<?php echo $this->url(array('action' => 'searchmission', 'selected' => 'ForMission', 'keyword' => '其他测试'));?>" class="keyword">其他测试</a>
</div>


<div id = 'allprojects'>

<?php  foreach($this->result as $value) :  ?>

<ul style="padding-left: 0px;">
 <li>
   <span class='missionid'>[<?php echo $this->escape($value['Mission_ID']);?>]</span>
   <span>  <a href="<?php echo $this->url(array('controller'=>'index', 
          'action'=>'missiondetail', 'fordetail_missionid' => $value['Mission_ID'] ));?>"><?php echo $this->escape($value['Mission_Name']);?></a> </span>
   <span style='float:right'>￥ <?php echo $this->escape($value['Lowest_Price']);?>~￥  <?php echo $this->escape($value['Highest_Price']);?></span>
 </li>
 
 <li>
   
   
   <span style='float:left'>  发布  <?php echo substr($this->escape($value['Release_Time']),0,10);?></span>
   <span>  <span class='missionid'>申请截止</span>  <?php echo substr($this->escape($value['Apply_Deadline']),0,10);?></span>
   <span>  完成截止  <?php echo substr($this->escape($value['Finish_Deadline']),0,10);?></span>
 </li>
 
 <li>
   <span><?php echo $this->escape($value['Tec_Field']);?></span>
   <span>  任务类型    <?php echo $this->escape($_SESSION['test_num_str'][$value['Mission_State']]);?></span>
   

 </li>
 <li>
   <span>简介   <?php echo $this->escape($value['Mission_About']);?></span>
 </li>
</ul>
<hr />
<?php endforeach; ?>




</div>

<h1> <?php echo $this->escape($this->message);?></h1>