
<style>

.username{
	
	font-weight: bold;
	color:#9393FF;
	font-family: Helv;
	font-size:30px;
}
.titles{
	
	color: #8CEA00;
}

}

</style>
   
   
<img src='<?php echo $this->baseUrl();?>/image/head.jpg' style="float: top; margin-right: 10px; margin-bottom: 15px;"/>   
<p ><span class="username"> <?php  echo $this->useraccount ['Account_Name']; ?></span> [<?php  echo $this->useraccount ['Account_ID']; ?>] 
<?php  if($this->useraccount ['Account_Sex']==0) echo '女'; else echo '男'; ?></p>
<p> <span class='titles'>联系方式：</span> <?php  echo $this->useraccount ['Account_Email']; ?>  <?php  echo $this->useraccount ['Account_mobile']; ?>  </p>


<p><span class='titles'>成交数量： </span><?php  echo $this->useralone ['Submittedmission_counts']; ?>  </p>
<p><span class='titles'>综合评分：</span> <?php  echo $this->useralone ['User_Averagescore']; ?>  </p>
<p><span class='titles'>自我评价 ： </span><?php  echo $this->useraccount ['Self_Discription']; ?>  </p>