
   
<p>姓名 ： <?php  echo $this->useraccount ['Account_Name']; ?>  </p>
<p>账号 ： <?php  echo $this->useraccount ['Account_ID']; ?>  </p>
<p>邮箱 ： <?php  echo $this->useraccount ['Account_Email']; ?>  </p>
<p>性别 ： <?php  echo $this->useraccount ['Account_Sex']; ?>  </p>
<p>手机 ： <?php  echo $this->useraccount ['Account_mobile']; ?>  </p>
<p>自我评价 ： <?php  echo $this->useraccount ['Self_Discription']; ?>  </p>
<p>综合评分： <?php  echo $this->useralone ['Submittedmissiono_counts']; ?>  </p>
<p>成交数量： <?php  echo $this->useralone ['User_Averagescore']; ?>  </p>