
  <div class="wrap">
    <ul class="site_info"><li><a href="#">了解我们</a> | <a href="#">我们的博客</a> | <a href="#">帮助中心</a> | <a href="#">联系我们</a> | <a href="#">合作伙伴</a> </li>

      <li>同济大学软件学院10届2班</li>
      <li>上海市曹安公路4800号</li>
      <li>Copyright © 2012, LOCALHOST, All Rights Reserved</li>
    </ul>
    <ul class="contact">
      <li class="email">E-Mail：<a href="#">doffery@163.com</a></li>
      <li class="tel">电话：010-12345678</li>
      <li class="qq">QQ：987654321</li>
      <li class="feedback"></li>
    </ul>
  </div>
