<ul id='menu_list'>
  <li><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'findallproject'));?>">找任务</a></li>
  <li><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'findalluser'));?>">找商家</a></li>
  <li><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'findalltester'));?>">找人才</a></li>
  <li><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'findallrecord'));?>">成功案例</a></li>
  <li><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'goprivatecenter'));?>">个人中心</a></li>
</ul>





