<?php if(isset($_SESSION['user'])) {?>
Hi! <a href="<?php
	echo $this->url ( array (
			'controller' => 'user',
			'action' => 'index' 
	) );
	?>"><?php echo $this->escape($_SESSION['user'])?></a>
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'logoff'));?>">注销</a>
<?php } else if(isset($_SESSION['tester'])) {?>
Hi! <a href="<?php
	echo $this->url ( array (
			'controller' => 'tester',
			'action' => 'index' 
	) );
	?>"><?php echo $this->escape($_SESSION['tester'])?></a>
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'logoff'));?>">注销</a>
<?php } else {?>
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'logon'));?>">登录</a>
	<a href="<?php echo $this->url(array('controller'=>'logon', 
        'action'=>'register'));?>">/注册</a>
<?php }?>