
<div>
<?php require_once 'testermenu.phtml';?>
</div>	

<img src="<?php echo $this->iconaddress;?>" title="icon" style="float: left; margin: 30px 20px 20px 20px; width: 98px; height: 98px;"/>
<h2><?php echo $this->escape($this->tester);?></h2>
<div style="font-size: 10px;">
<p>速度评价：<?php echo $this->escape($this->quality_score);?></p>
<p>质量评价：<?php echo $this->escape($this->timing_score);?></p>
<p>态度评价：<?php echo $this->escape($this->mate_score);?></p>
<p>完成的任务数：<?php echo $this->escape($this->missioncount);?></p>
</div>


<h2>最近申请的任务</h2>
	<table>
		<tr>
			<th>任务编号</th>
			<th>任务名称</th>
			<th>任务类型</th>
			<th>任务发布时间</th>
			<th>父任务</th>
		</tr>
<?php foreach ($this->testermissions as $tum) :?>
		<tr>
			<td><?php echo $this->escape($tum['Mission_ID']);?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'tester', 
        'action'=>'missionfulfil', 'missionid' => $tum['Mission_ID']));?>"><?php echo $this->escape($tum['Mission_Name']);?></a></td>
			<td><?php echo $this->escape($_SESSION['test_num_str'][$tum['Mission_State']]);?></td>
			<td><?php echo $this->escape($tum['Release_Time']);?></td>
			<td><?php echo $this->escape($tum['Father_Mission'])?$this->escape($tum['Father_Mission']):'X';?></td>
		</tr>
<?php endforeach;?>
	</table>