<h2><?php echo $this->missionname;?></h2>
<p title="<?php echo $this->applytime;?>">申请时间：<?php echo substr($this->applytime, 0, 10);?></p>
<p title="<?php echo $this->gettime;?>">接受时间：<?php echo substr($this->gettime, 0, 10);?></p>

<?php if(!$this->begintime) {?>
<h2>您还没有开始本测试任务：</h2>
<p>点击开始</p>
<form action="<?php echo $this->url(array('controller' => 'tester', 'action' => 'missionfulfil'));?>" method="post">

<input type="hidden" name="missionid" value="<?php echo $this->missionid?>"/>
<input type="hidden" name="commandtype" value="start"/>

<input type="submit" name="submit" value="开始"/>
</form>
<?php } else {?>
交付时间：<?php echo $this->deadline;?>
任务简介：<?php echo $this->missionabout;?>
<br />
<h3>用户上传的文件：</h3>
<?php
$dir = "D:/www/TaskAllocatePro/files/".$this->missionid."/user/";
// Open a known directory, and proceed to read its contents
if (is_dir($dir)) {
    if ($dh = opendir($dir)) {
        while (($file = readdir($dh)) !== false) {
        if($file != "." && $file !=".."  ){
			echo  '文件名称：';
			echo  '<a href="http://localhost/TaskAllocatePro/files/'.$this->missionid.'/user/'.$file.'">'.$file.'</a>';
			echo  '<br />';
		}
	}
        closedir($dh);
    }
}
?>
<h3>您上传的文件：</h3>
<?php
$dir = "D:/www/TaskAllocatePro/files/".$this->missionid."/tester/";
// Open a known directory, and proceed to read its contents
if (is_dir($dir)) {
    if ($dh = opendir($dir)) {
        while (($file = readdir($dh)) !== false) {
        if($file != "." && $file !=".." ){
			echo  '文件名称：';
			echo  $file;
			echo  '<br />';
		}	
	}
        closedir($dh);
    }
}
?>
<form enctype="multipart/form-data" action="<?php echo $this->url(array('controller' => 'tester', 'action'=>'missionfulfil')); ?>" method="post">

    <br>
  <input name="uploadfile" type="file">
    <br>
    <input name= "upload" type="submit" value="上传文件">
</form>
<?php if(isset($this->submission)) {?>
<h2>子任务</h2>
<?php foreach ($this->submission as $sm) :?>
	<p style="font-size: 14px;"><a href="<?php echo $this->url(array('controller'=>'tester', 'action'=>'missionfulfil',
			 'missionid' => $sm['Mission_ID']));?>"><?php echo $this->escape($sm['Mission_Name']);?></a><span style="font-size: 10px;">[<?php echo $this->escape($sm['Mission_ID']);?>]</span></p>

	<p style="font-size: 15px; width: 200px;"><?php echo $this->escape($_SESSION['test_num_str'][$sm['Mission_State']]);?>
	<span style="font-size: 10px;"><?php echo $this->escape($sm['Tec_Field']);?></span></p>

	<p style="font-size: 10px;">￥<?php echo $this->escape($sm['Lowest_Price']);?>-￥<?php echo $this->escape($sm['Highest_Price']);?>
	<?php echo substr($this->escape($sm['Release_Time']), 0, 10);?></p>
	<?php $this->escape($sm['Father_Mission'])?$this->escape($sm['Father_Mission']):'X';?>

		<?php endforeach; }?>
		
		<a href="<?php echo $this->url(array('controller'=>'tester', 'action'=>'missiondialy',
			 'missionid' => $this->missionid));?>">日志</a>
		<a href="<?php echo $this->url(array('controller'=>'tester', 'action'=>'missionsubmit',
			 'missionid' => $this->missionid));?>">完成任务</a>
		<a href="<?php echo $this->url(array('controller'=>'tester', 'action'=>'tradeinfo',
			 'missionid' => $this->missionid));?>">确认到账</a>
			 
<?php }?>