
<div>
<?php require_once 'testermenu.phtml';?>
</div>
<form action="<?php echo $this->url(array('controller' => 'tester', 'action'=>'testerdata')); ?>" method="post">
<img src="<?php echo $this->baseUrl();?>/image/head.jpg" title="暂无头像功能" style="float: left; margin: 0px 20px 20px 20px;"/>
<h2><?php echo $this->escape($this->name);?></h2>
<div style="margin-left: 10px; margin-top: 100px;">
<p>性别：<select name="sex" >
<?php if ($this->sex == 1) {?>
        <option value ="1">男</option>
        <option value ="0">女</option>
<?php } else {?>
        <option value ="0">女</option>
        <option value ="1">男</option>
<?php }?>
   </select></p>
<p>邮箱：<input type="email" name="email" value="<?php echo $this->escape($this->email);?>" disabled="disabled"/></p>
<p>电话：<input type="text" name="mobile" value="<?php echo $this->escape($this->mobile);?>" /></p>
</div>
<div style="margin-left: 10px; margin-top: 40px;">
<p>自我描述：</p>
	<textarea name="selfdiscription" id="selfdiscription" cols="40" rows="2" style="margin-left: 10px"><?php echo $this->escape($this->selfdiscription);?></textarea>
</div>
<div>
<input type="submit" name="change" value="更改" />
<input type="submit" name="change" value="取消" />
</div>
</form>

