<!-- 
<div>
<?php //require_once 'testermenu.phtml';?>
</div>
<form action="<?php echo $this->url(array('controller' => 'tester', 'action'=>'testerdata')); ?>" method="post">
<img src="<?php echo $this->baseUrl();?>/image/head.jpg" title="暂无头像功能" style="float: left; margin: 0px 20px 20px 20px;"/>
<h2><?php echo $this->escape($this->name);?></h2>
<div style="margin-left: 10px; margin-top: 100px;">
<p>性别：<select name="sex" >
<?php if ($this->sex == 1) {?>
        <option value ="1">男</option>
        <option value ="0">女</option>
<?php } else {?>
        <option value ="0">女</option>
        <option value ="1">男</option>
<?php }?>
   </select></p>
<p>邮箱：<input type="email" name="email" value="<?php echo $this->escape($this->email);?>" disabled="disabled"/></p>
<p>电话：<input type="text" name="mobile" value="<?php echo $this->escape($this->mobile);?>" /></p>
</div>
<div style="margin-left: 10px; margin-top: 40px;">
<p>自我描述：</p>
	<textarea name="selfdiscription" id="selfdiscription" cols="40" rows="2" style="margin-left: 10px"><?php echo $this->escape($this->selfdiscription);?></textarea>
</div>
<div>
<input type="submit" name="change" value="更改" />
<input type="submit" name="change" value="取消" />
</div>
</form>
 -->
 
<div>
<?php require_once 'testermenu.phtml';?>
</div>
<img src="<?php echo $this->iconaddress;?>" title="头像" style="float: left; margin: 30px 20px 20px 20px; width: 98px; height: 98px;"/>
<h2><?php echo $this->escape($this->name);?></h2>
<form enctype="multipart/form-data" action="<?php echo $this->url(array('controller' => 'user', 'action'=>'userdata')); ?>" method="post">

    <br>
  <input name="uploadfile" id="uploadfile" type="file">
    <br>
    <input name= "upload" type="submit" value="上传头像">
</form>
<form action="<?php echo $this->url(array('controller' => 'tester', 'action'=>'testerdata')); ?>" method="post">
<div style="margin-left: 10px; margin-top: 100px;">

<p>性别：<select name="sex" >
<?php if ($this->sex == 1) {?>
        <option value ="1">男</option>
        <option value ="0">女</option>
<?php } else {?>
        <option value ="0">女</option>
        <option value ="1">男</option>
<?php }?>
   </select></p>
<p>邮箱：<input type="email" name="email" value="<?php echo $this->escape($this->email);?>" disabled="disabled"/></p>
<p>电话：<input type="text" name="mobile" value="<?php echo $this->escape($this->mobile);?>" /></p>
</div>
<div style="margin-left: 10px; margin-top: 40px;">
<p>自我描述：</p>
	<textarea name="selfdiscription" id="selfdiscription" cols="40" rows="2" style="margin-left: 10px"><?php echo $this->escape($this->selfdiscription);?></textarea>
</div>
<div>
<input type="submit" name="change" value="更改" />
<input type="submit" name="change" value="取消" />
</div>
</form>
<script type="text/javascript">
function chk () {
	 Ary = 	document.getElementById("uploadfile").value.split('.');
	 filetype=Ary[Ary.length-1];
	 if (filetype!='jpg'&&filetype!='JPG') 
	  {
	     alert ("请上传jpg格式的头像文件");
	     return false;
	  }
	 return true;
}
</script>

 
