<div>
<?php require_once 'testermenu.phtml';?>
</div>

<div>
	<h2>收到的消息(最近一个月)</h2>
<?php foreach ($this->tmessageReceive as $tmp) :?>
<div>
<hr />
		<h3><?php echo $tmp['Message_Title'];?></h3>
		<a href="<?php echo $this->url(array('controller' => 'message',
				 'action' => 'detail', 'messageid' => $tmp['Message_ID']));
		?>" target="_blank" style="float: right;">阅读</a>
		
		<?php if($tmp['ReadOrnot']) {?>
		<p>已读</p>
		<?php } else {?>
		<p>未读</p>
		<?php }?>
			消息来源：<a href="<?php echo $this->url(array('controller' => 'index',
					 'action' => 'userdetail',
					 'fordetail_userid' => $tmp['Publisher_ID']));
			?>"><?php echo $this->getAccountNameById($tmp['Publisher_ID']);?></a>
		消息发布时间：<?php echo $tmp['Publish_Time'];?>
			相关任务：<a href="<?php echo $this->url(array('controller' => 'tester',
					 'action' => 'missionfulfil',
					 'missionid' => $tmp['Related_Mission_ID']));
			?>"><?php echo $this->getMissionNameById($tmp['Related_Mission_ID']);?></a>
		
</div>
<?php endforeach;?>
<a href="#">查看全部</a>
</div>
<div>
<hr />
<hr />
	<h2>我发布的消息(最近一个月)</h2>
<?php foreach ($this->tmessagePublish as $tmr) :?>
<div>
<hr />
		<h3><?php echo $tmr['Message_Title'];?></h3>
		<a href="<?php echo $this->url(array('controller' => 'message',
				 'action' => 'detail', 'messageid' => $tmr['Message_ID']));
		?>" target="_blank" style="float: right;">查看</a>
			消息发往：<a href="<?php echo $this->url(array('controller' => 'index',
					 'action' => 'userdetail',
					 'fordetail_userid' => $tmr['Receiver_ID']));
			?>"><?php echo $this->getAccountNameById($tmr['Receiver_ID']);?></a>
		          消息发布时间：<?php echo $tmr['Publish_Time'];?>
		
			相关任务：<a href="<?php echo $this->url(array('controller' => 'tester',
					 'action' => 'missionfulfil',
					 'missionid' => $tmr['Related_Mission_ID']));
			?>"><?php echo $this->getMissionNameById($tmr['Related_Mission_ID']);?></a>
		
</div>
<?php endforeach;?>
<a href="#">查看全部</a>
</div>