<p><?php echo $this->notice?></p>
<form action="<?php echo $this->url(array('controller' => 'tester', 'action' => 'tradeinfo'));?>"
	method="post" onsubmit="_check()">
	<input type="hidden" name="missionid" value="<?php echo $this->missionid;?>" />
	<input type="number" name="price" id="price"/>
<input type="submit" name="submit" value="确定"/>
	
</form>


<script>

function _check() {
	if(document.getElementById('price').value == "") {
		alert("请输入一个金额！");
		return false;
	}
	return true;
}
</script>