<h1>选择系统测试的具体内容</h1>
<p>你可以同时选择多个具体的测试内容</p>
<?php echo $this->t;?>
<form
	action="<?php echo $this->url(array('controller'=>'mission', 'action'=>'publishmissions')); ?>"
	method="post" onsubmit="return _validate();">
	<p>系统测试名称<input type="text" name="missionname" id="missionname" maxLength=40 /></p>
	<table>
		<tr>
			<td><input type="checkbox" name="testtype1" id="testtype1"></td>
			<td>功能测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype2" id="testtype2"></td>
			<td>安全性测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype3" id="testtype3"></td>
			<td>容量测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype4" id="testtype4"></td>
			<td>完整性测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype5" id="testtype5"></td>
			<td>结构测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype6" id="testtype6"></td>
			<td>用户界面测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype7" id="testtype7"></td>
			<td>负载测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype8" id="testtype8"></td>
			<td>压力测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype9" id="testtype9"></td>
			<td>疲劳强度测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype10" id="testtype10"></td>
			<td>恢复性测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype11" id="testtype11"></td>
			<td>配置测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype12" id="testtype12"></td>
			<td>兼容性测试</td>
		</tr>
		<tr>
			<td><input type="checkbox" name="testtype13" id="testtype13"></td>
			<td>安装测试</td>
		</tr>
	</table>
	<p><input type="checkbox" name="separate">任务分开发布</p>
	<p>选择分开发布后，您将分别需要发布您的小任务，这些任务一般会被不同的测试人员接受</p>
	<p>任务如若不分开发布，将会由一个测试人员接受</p>
	<input type="submit" name="submit" value="继续">
</form>


<script>
function _validate() {
	if(document.getElementById("testtype1").checked || document.getElementById("testtype2").checked
		 || document.getElementById("testtype3").checked || document.getElementById("testtype4").checked
			  || document.getElementById("testtype5").checked || document.getElementById("testtype6").checked 
				  || document.getElementById("testtype7").checked || document.getElementById("testtype8").checked
					   || document.getElementById("testtype9").checked || document.getElementById("testtype10").checked
						    || document.getElementById("testtype11").checked || document.getElementById("testtype12").checked
							     || document.getElementById("testtype13").checked) {
		return true;
	}
    alert("请至少选择一种任务类型！");
	return false;
}

</script>