
<a href="<?php echo $this->url(array(
								'controller' => 'user',
								'action' => 'index' ));?>">商家首页</a>
<a href="<?php echo $this->url(array(
								'controller' => 'user',
								'action' => 'userdata' ));?>">商家资料</a>
<a href="<?php echo $this->url(array(
								'controller' => 'user',
								'action' => 'usermission' ));?>">项目管理</a>
<a href="<?php echo $this->url(array(
								'controller' => 'user',
								'action' => 'usermessage' ));?>">我的消息</a>