
<!-- 
<div>
<?php //require_once 'usermenu.phtml';?>
</div>
<form action="<?php echo $this->url(array('controller' => 'user', 'action'=>'userdata')); ?>" method="post" id="formuser" name="formuser">
<img src="<?php echo $this->baseUrl();?>/image/head.jpg" title="暂无头像功能" style="float: left; margin: 0px 20px 20px 20px;"/>
<h2><?php echo $this->escape($this->name);?></h2>
<div style="margin-left: 10px; margin-top: 100px;">
<p>性别：<select name="sex" >
<?php if ($this->sex == 1) {?>
        <option value ="1">男</option>
        <option value ="0">女</option>
<?php } else {?>
        <option value ="0">女</option>
        <option value ="1">男</option>
<?php }?>
   </select></p>
<p>邮箱：<input type="email" name="email" value="<?php echo $this->escape($this->email);?>" disabled="disabled"/></p>
<p>电话：<input type="tel" name="mobile" id="mobile" value="<?php echo $this->escape($this->mobile);?>" /></p>
</div>
<div style="margin-left: 10px; margin-top: 40px;">
<p>自我描述：</p>
	<textarea name="selfdiscription" id="selfdiscription" cols="40" rows="2" style="margin-left: 10px"><?php echo $this->escape($this->selfdiscription);?></textarea>
</div>
<div>
<input type="button" name="change" onclick="_check()" value="更改" />
<input type="submit" name="change" value="取消" />
</div>
</form>
<a href="#">申请成为测试人员</a>

<script>
function _check() {
	if(document.getElementById("mobile").value != "" && !isTel(document.getElementById("mobile").value)) {
		alert("请输入正确的电话！");
		return;
		}
	else this.formuser.submit();
}


function isTel(str){
    var reg = /((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$)/;
    return reg.test(str);
}
</script>
 -->
 
 
<div>
<?php require_once 'usermenu.phtml';?>
</div>

<img src="<?php echo $this->iconaddress;?>" title="icon" style="float: left; margin: 30px 20px 20px 20px; width: 98px; height: 98px;"/>

<h2><?php echo $this->escape($this->name);?></h2>
<form enctype="multipart/form-data" action="<?php echo $this->url(array('controller' => 'user', 'action'=>'userdata')); ?>" method="post"  onsubmit="return chk();">

    <br>
  <input name="uploadfile" id="uploadfile" type="file">
    <br>
    <input name= "upload" type="submit"  value="上传头像" >
</form>

<form action="<?php echo $this->url(array('controller' => 'user', 'action'=>'userdata')); ?>" method="post" id="formuser" name="formuser">
<div style="margin-left: 10px; margin-top: 100px;">
<p>性别：<select name="sex" >
<?php if ($this->sex == 1) {?>
        <option value ="1">男</option>
        <option value ="0">女</option>
<?php } else {?>
        <option value ="0">女</option>
        <option value ="1">男</option>
<?php }?>
   </select></p>
<p>邮箱：<input type="email" name="email" value="<?php echo $this->escape($this->email);?>" disabled="disabled"/></p>
<p>电话：<input type="tel" name="mobile" id="mobile" value="<?php echo $this->escape($this->mobile);?>" /></p>
</div>
<div style="margin-left: 10px; margin-top: 40px;">
<p>自我描述：</p>
	<textarea name="selfdiscription" id="selfdiscription" cols="40" rows="2" style="margin-left: 10px"><?php echo $this->escape($this->selfdiscription);?></textarea>
</div>
<div>
<input type="button" name="change" onclick="_check()" value="更改" />
<input type="submit" name="change" value="取消" />
</div>
</form>

<br />
<a href="#">申请成为测试人员</a>

<script>
function _check() {
	if(document.getElementById("mobile").value != "" && !isTel(document.getElementById("mobile").value)) {
		alert("请输入正确的电话！");
		return false;
		}
	else this.formuser.submit();
	return true;
}

function chk () {
 Ary = 	document.getElementById("uploadfile").value.split('.');
 filetype=Ary[Ary.length-1];
 if (filetype!='jpg'&&filetype!='JPG') 
  {
     alert ("请上传jpg格式的头像文件");
     return false;
  }
 return true;
}

function isTel(str){
    var reg = /((\d{11})|^((\d{7,8})|(\d{4}|\d{3})-(\d{7,8})|(\d{4}|\d{3})-(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1})|(\d{7,8})-(\d{4}|\d{3}|\d{2}|\d{1}))$)/;
    return reg.test(str);
}
</script>