
<div>
<?php require_once 'usermenu.phtml';?>
</div>

<h2>所有任务:</h2>
	<table>
		<tr>
			<th>任务编号</th>
			<th>任务名称</th>
			<th>任务类型</th>
			<th>任务发布时间</th>
			<th>父任务</th>
		</tr>
<?php foreach ($this->usermissions as $um) :?>
		<tr>
			<td><?php echo $this->escape($um['Mission_ID']);?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'mission', 'missionid' => $um['Mission_ID']));?>"><?php echo $this->escape($um['Mission_Name']);?></a></td>
			<td><?php echo $this->escape($_SESSION['test_num_str'][$um['Mission_State']]);?></td>
			<td><?php echo $this->escape($um['Release_Time']);?></td>
			<td><?php echo $this->escape($um['Father_Mission'])?$this->escape($um['Father_Mission']):'X';?></td>
		</tr>
<?php endforeach;?>
	</table>