

<form action="<?php echo $this->url(array('controller' => 'user',
		 'action'=>'valuatetester')); ?>" method="post">
<input type="hidden" name="missionid" value="<?php echo $this->missionid;?>" />
<p>完成速度</p>
<input type="range" name="timingscore" id="timingscorerange" onchange="_timingscore()"/>
<input type="number" name="timingscore" id="timingscore" readonly="readonly" value="50"/>

<p>完成质量</p>
<input type="range" name="qualityscore" id="qualityscorerange" onchange="_qualityscore()"/>
<input type="number" name="qualityscore" id="qualityscore" readonly="readonly" value="50"/>

<p>配合态度</p>
<input type="range" name="matescore" id="matescorerange" onchange="_matescore()"/>
<input type="number" name="matescore" id="matescore" readonly="readonly" value="50"/>

<textarea name="comment" id="comment" cols="50" rows="5"
	onfocus="if (this.value=='不少于5个字') this.value='';">不少于5个字</textarea>
	<input type="submit" name="submit" value="确定"/>
</form>
<script type="text/javascript">
function _timingscore() {
	document.getElementById('timingscore').value = document.getElementById('timingscorerange').value;
}

function _qualityscore() {
	document.getElementById('qualityscore').value = document.getElementById('qualityscorerange').value;
}

function _matescore() {
	document.getElementById('matescore').value = document.getElementById('matescorerange').value;
}
</script>