<style>
<!--
#mission_space div{
	height:50px;
}
#mission_info{
	height:100px;
}
#mission_info textarea{
	height:80px;
	width:200px;
}
#mission_space div label{
	float:left;
	width:120px;
	display: inline-block;
	text-align:left
}
#mission_space div input{
	display: inline-block;
}
#submit_button {
	margin-top: 50px;
	width:50px;
	height:30px;
	font-size:18px;
}
-->
</style>
<form
	action="<?php echo $this->url(array('controller'=>'publishmission', 'action'=>'publishmission1')); ?>"
	method="post" onsubmit="return _validate();">
	<input type="hidden" name="missiontype" value="<?php echo 1;?>" />
	<input type="hidden" name="missionvisible" value="<?php echo 1;?>" />
	<div id="mission_space">
	<div>
		<label>任务名称</label>
		<input type="text" name="missionname" id="missionname" maxLength=40 />
	</div>
	<div>
		<label>价格区间</label>
		<input type="number" name="lowprice" id="lowprice" />~
		<input type="number" name="highprice" id="highprice" />元
	</div>
	<div>
		<label>申请截止日期</label>
		<input type="date" name="applicationdate"
			id="applicationdate" onclick="new Calendar().show(this);" readonly="readonly" />
	</div>
	<div>
		<label>任务完成日期</label>
		<input type="date" name="finishdate"
		 id="finishdate"  onclick="new Calendar().show(this);" readonly="readonly"/>
	</div>
	<div>
		<label>任务技术领域</label>
		<input type="text" name="tecfield" id="tecfield" />
	</div>
	<div id="mission_info">
	<label>任务简介</label>
	<textarea name="missioncontent" id="missioncontent" cols="" rows=""
		onfocus="if (this.value=='不少于5个字') this.value='';">不少于5个字</textarea>
	</div>
	</div>
	<input id="submit_button" type="submit" name="submit" id="submit" value="发布" />
</form>
<script>
//验证表单是否为空
function _validate(){
	if(document.getElementById('missionname').value=="" || document.getElementById('lowprice').value=="" || document.getElementById('highprice').value=="" || 
			 document.getElementById('applicationdate').value=="" || document.getElementById('finishdate').value=="" || 
			 document.getElementById('tecfield').value=="" || document.getElementById('missioncontent').value==""){
		alert("请输入完整信息");
		return false;
	}
	//else if (document.getElementById('missionname').value.length )
	else if(parseFloat(document.getElementById('lowprice').value) >= parseFloat(document.getElementById('highprice').value)) {
		alert("请输入正确价格信息！");
		return false;
	}
	else if(parseFloat(document.getElementById('lowprice')).value < 0 || parseFloat(document.getElementById('highprice').value >= 1000000)) {

		alert("请输入合理的价格信息！");
		return false;
	}
	else if(!duibi(document.getElementById('applicationdate').value, document.getElementById('finishdate').value)){

		alert("请输入合理的时间信息！");
		return false;
	}

	return true;
}

function duibi(a, b) {
    var arr = a.split("-");
    var starttime = new Date(arr[0], arr[1], arr[2]);
    var starttimes = starttime.getTime();

    var arrs = b.split("-");
    var lktime = new Date(arrs[0], arrs[1], arrs[2]);
    var lktimes = lktime.getTime();

	
    if (starttimes >= lktimes) {

        return false;
    }
    else
        return true;
}
</script>