
<form
	action="<?php echo $this->url(array('controller'=>'publishmission', 'action'=>'publishmissionrdetail')); ?>"
	method="post">
	<input type="hidden" name="fathermission" value="<?php echo $_SESSION['fathermission2'];?>" />
	<table>
		<tr>
			<th></th>
			<th>任务编号</th>
			<th>任务名称</th>
			<th>任务类型</th>
			<th>任务发布时间</th>
			<th>父任务</th>
		</tr>
<?php foreach ($this->usermissions as $um) :?>
<?php if($um[Mission_ID] != $_SESSION['fathermission2']) {?>
		<tr>
			<td><input type="checkbox" name="missionadd<?php echo $um['Mission_ID'];?>" id="missionadd<?php echo $um['Mission_ID'];?>" /></td>
			<td><?php echo $this->escape($um['Mission_ID']);?></td>
			<td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'mission', 'missionid' => $um['Mission_ID']));?>" target="_blank"><?php echo $this->escape($um['Mission_Name']);?></a></td>
			<td><?php echo $this->escape($_SESSION['test_num_str'][$um['Mission_State']]);?></td>
			<td><?php echo $this->escape($um['Release_Time']);?></td>
			<td><?php echo $this->escape($um['Father_Mission'])?$this->escape($um['Father_Mission']):'X';?></td>
		</tr>
<?php }endforeach;?>
	</table>
	
	<input type="submit" name="submit" id="submit" value="确定">
</form>